batch_size: 4
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202510280421
train_epochs: 150
train_workers: 4
vocab: xzWBmbnyFX t?dIu3R0Uvpgc/ZD+s4!i2w&VjqH-kE58MQL)Jf:'l6e(;KS*hAaY#o1P9"7Cr.T,ONG
width: 1408
