batch_size: 8
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202511030107
train_epochs: 700
train_workers: 4
vocab: NEA#ag!i'YRZqW0,z4mo)*Ms:d(pFBOuvn/3QXx+9fHjh1DtI&;?Kc"w5b8GJ6VPCUreyklST 2.L-7
width: 1408
